#!/bin/bash
set -eu

GREEN='\e[32m'
RED='\e[31m'
GREY='\033[38;5;250m'
RESET='\e[0m'

WIDTH=10
HEIGHT=1.5
FAILS=2

FILEPATH="formulas.typ"
TEMP_FILE=$(mktemp)

clear_() {
	if [[ -e "$TEMP_FILE" ]]; then
		rm "$TEMP_FILE"
		rm "${TEMP_FILE}.png"
	fi
	is_correct=-1
	formula=""
}

clear_and_exit() {
	clear_
	clear
	exit
}

save_ifs() {
	original_IFS=$IFS
	IFS=$'\n'
}

recover_ifs() {
	IFS="$original_IFS"
}

print_image() {
	echo "#set page(width: ${WIDTH}cm, height: ${HEIGHT}cm)" > "$TEMP_FILE"
	echo "$correct_answer" >> "$TEMP_FILE"

	if [[ ! -e "${TEMP_FILE}.png" ]]; then
		typst compile "$TEMP_FILE" -f png "${TEMP_FILE}.png"
	fi
	chafa --align center "${TEMP_FILE}.png" </dev/null
}

get_typed_formula() {
	if [[ $is_correct == 1 ]]; then
		echo -e "${GREEN}Correct${RESET}"
	elif [[ $is_correct == 0 ]]; then
		echo -e "${RED}Incorrect${RESET}"
	fi

	save_ifs
	read -r -e -p "> " -i "$input_formula" input_formula
	recover_ifs
}

trim_whitespaces_formula() {
	set -f
	set -- "$@"
	printf "%s" "$*"
	set +f
}

trim_formula() {
	local formula
	formula=$(trim_whitespaces_formula $1)
	formula="${formula#$}"
	formula="${formula%$}"
	formula=$(trim_whitespaces_formula $formula)
	printf "%s" "$formula"
}

check_typed_formula() {
	correct_answer=$(trim_formula "$correct_answer")
	input_formula=$(trim_formula "$input_formula")
	if [[ "$input_formula" == "$correct_answer" ]]; then
		is_correct=1
	else
		is_correct=0
		fails=$((fails-1))
	fi
}

print_header() {
	echo
	clear
	echo -e " ${GREY}Fails: $fails$RESET"
	echo

}

print_error_message() {
	echo -e "${RED}Incorrect$RESET"
}

print_correct_message() {
	echo -e "${GREEN}Correct$RESET"
	echo
}

print_correct_answer() {
	correct_answer=$(trim_formula "$correct_answer")
	echo
	echo -e "${GREEN}Correct answer: $correct_answer$RESET"
	echo
}

check_filepath() {
	if [[ ! -e $FILEPATH ]]; then
		echo "filepath doesn't exist"
		exit 1
	fi
}

suggest_next_task() {
	save_ifs
	read -r -p "next task? [Y/n]: " choice
	recover_ifs

	if [[ $choice == "" ]]; then
		choice="Y"
	fi
}

main() {
	check_filepath

	input_formula=""
	is_correct=-1
	while true; do
		correct_answer=$(shuf -n 1 "$FILEPATH")
		fails=$FAILS
		while [[ $fails != 0 ]]; do
			print_header
			print_image
			get_typed_formula
			check_typed_formula

			if [[ $is_correct == 1 || $fails == 0 ]]; then
				if [[ $fails == 0 ]]; then
					if [[ $FAILS == 1 ]]; then
						print_error_message
					fi
					print_correct_answer
				else
					print_correct_message
				fi

				suggest_next_task
				if [[ "$choice" == "y" || "$choice" == "Y" ]]; then
					clear_;
					break;
				else
					clear_and_exit
				fi
			fi
		done
	done

	clear_and_exit
}

run_trap() {
	trap clear_and_exit SIGINT
	trap clear_and_exit SIGTERM
	trap clear_and_exit SIGQUIT
	trap clear_and_exit EXIT
}

run_trap

main
