#!/bin/bash
set -eu

GREEN='\e[32m'
RED='\e[31m'
GREY='\033[38;5;250m'
RESET='\e[0m'

WIDTH=10
HEIGHT=1.5

IFS='\n'
FILEPATH="formulas.typ"
TEMP_FILE=$(mktemp)

exit_() {
	rm "$TEMP_FILE"
}

print_image() {
	echo "#set page(width: ${WIDTH}cm, height: ${HEIGHT}cm)" > "$TEMP_FILE"
	echo "$line" >> "$TEMP_FILE"
	typst compile "$TEMP_FILE" -f png - | chafa --align center
}

get_typed_formula() {
	if [[ $is_correct == 1 ]]; then
		echo -e "${GREEN}correct${RESET}"
		formula=""
	elif [[ $is_correct == 0 ]]; then
		echo -e "${RED}incorrect${RESET}"
	fi
	read -e -p "> " -i "$formula" formula
}

trim_formula() {
	trimmed_line=${line#$}
	trimmed_line=${trimmed_line%$}
	trimmed_line=${trimmed_line# }
	trimmed_line=${trimmed_line% }
}

check_typed_formula() {
	trim_formula
	if [[ "$formula" == "$trimmed_line" ]]; then
		is_correct=1
	else
		is_correct=0
		fails=$((fails-1))
	fi
}

print_header() {
	clear
	echo
	echo -e " ${GREY}Fails: $fails$RESET"
	echo
}

check_filepath() {
	if [[ ! -e $FILEPATH ]]; then
		echo "filepath doesn't exist"
		exit 1
	fi
}

suggest_next_task() {
	echo -e "${GREEN}correct${RESET}"
	read -p "next task? [y/n]: " choice
}

main() {
	check_filepath

	result=""
	formula=""
	is_correct=-1
	while true; do
		line=$(shuf -n 1 "$FILEPATH")
		fails=5
		while [[ $fails != 0 ]]; do
			print_header
			print_image
			get_typed_formula
			check_typed_formula

			if [[ $is_correct == 1 ]]; then
				suggest_next_task
				if [[ $choice == "y" ]]; then
					break;
				else
					exit_
					exit
				fi
			fi
		done
	done

	echo "tasks are ended"
	exit_
}

main
